In [1]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [2]:
from transformers import pipeline
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = device)
classifier("I love this!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

[[{'label': 'joy', 'score': 0.9771686792373657},
  {'label': 'surprise', 'score': 0.008528703823685646},
  {'label': 'neutral', 'score': 0.005764608271420002},
  {'label': 'anger', 'score': 0.004419793840497732},
  {'label': 'sadness', 'score': 0.002092394046485424},
  {'label': 'disgust', 'score': 0.0016119952779263258},
  {'label': 'fear', 'score': 0.00041385236545465887}]]

In [3]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [4]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.654841423034668},
  {'label': 'neutral', 'score': 0.16985175013542175},
  {'label': 'sadness', 'score': 0.1164090484380722},
  {'label': 'surprise', 'score': 0.020700618624687195},
  {'label': 'disgust', 'score': 0.019100729376077652},
  {'label': 'joy', 'score': 0.015161292627453804},
  {'label': 'anger', 'score': 0.003935151267796755}]]

In [5]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296028733253479},
  {'label': 'neutral', 'score': 0.14038577675819397},
  {'label': 'fear', 'score': 0.06816203892230988},
  {'label': 'joy', 'score': 0.04794236272573471},
  {'label': 'anger', 'score': 0.00915634073317051},
  {'label': 'disgust', 'score': 0.002628473099321127},
  {'label': 'sadness', 'score': 0.002122159581631422}],
 [{'label': 'neutral', 'score': 0.44937023520469666},
  {'label': 'disgust', 'score': 0.273592084646225},
  {'label': 'joy', 'score': 0.10908293724060059},
  {'label': 'sadness', 'score': 0.09362714737653732},
  {'label': 'anger', 'score': 0.040478307753801346},
  {'label': 'surprise', 'score': 0.02697017230093479},
  {'label': 'fear', 'score': 0.006879056338220835}],
 [{'label': 'neutral', 'score': 0.6462165713310242},
  {'label': 'sadness', 'score': 0.24273282289505005},
  {'label': 'disgust', 'score': 0.043422624468803406},
  {'label': 'surprise', 'score': 0.028300536796450615},
  {'label': 'joy', 'score': 0.014211492612957954},
  {'label': 'fear', 'score': 0.014084096997976303},
  {'label': 'anger', 'score': 0.01103188656270504}],
 [{'label': 'fear', 'score': 0.9281684160232544},
  {'label': 'anger', 'score': 0.032190777361392975},
  {'label': 'neutral', 'score': 0.012808679603040218},
  {'label': 'sadness', 'score': 0.00875687226653099},
  {'label': 'surprise', 'score': 0.008597918786108494},
  {'label': 'disgust', 'score': 0.00843181274831295},
  {'label': 'joy', 'score': 0.0010455820010975003}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104178339242935},
  {'label': 'disgust', 'score': 0.006480599287897348},
  {'label': 'fear', 'score': 0.0053939977660775185},
  {'label': 'surprise', 'score': 0.0022869440726935863},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.001733880490064621}],
 [{'label': 'joy', 'score': 0.9327977299690247},
  {'label': 'disgust', 'score': 0.037717387080192566},
  {'label': 'neutral', 'score': 0.015891926363110542},
  {'label': 'sadness', 'score': 0.006444522179663181},
  {'label': 'anger', 'score': 0.005024992395192385},
  {'label': 'surprise', 'score': 0.0015812095953151584},
  {'label': 'fear', 'score': 0.0005423080874606967}],
 [{'label': 'joy', 'score': 0.6528699398040771},
  {'label': 'neutral', 'score': 0.254275381565094},
  {'label': 'surprise', 'score': 0.06808310747146606},
  {'label': 'sadness', 'score': 0.009908986277878284},
  {'label': 'disgust', 'score': 0.006512207444757223},
  {'label': 'anger', 'score': 0.004821314476430416},
  {'label': 'fear', 'score': 0.003529014065861702}],
 [{'label': 'neutral', 'score': 0.5494765639305115},
  {'label': 'sadness', 'score': 0.1116902306675911},
  {'label': 'disgust', 'score': 0.10400673747062683},
  {'label': 'surprise', 'score': 0.07876552641391754},
  {'label': 'anger', 'score': 0.0641336515545845},
  {'label': 'fear', 'score': 0.051362842321395874},
  {'label': 'joy', 'score': 0.040564440190792084}]]

In [6]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [7]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [8]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296028733253479},
 {'label': 'neutral', 'score': 0.14038577675819397},
 {'label': 'fear', 'score': 0.06816203892230988},
 {'label': 'joy', 'score': 0.04794236272573471},
 {'label': 'anger', 'score': 0.00915634073317051},
 {'label': 'disgust', 'score': 0.002628473099321127},
 {'label': 'sadness', 'score': 0.002122159581631422}]

In [9]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [10]:
predictions[3]

[{'label': 'fear', 'score': 0.9281684160232544},
 {'label': 'anger', 'score': 0.032190777361392975},
 {'label': 'neutral', 'score': 0.012808679603040218},
 {'label': 'sadness', 'score': 0.00875687226653099},
 {'label': 'surprise', 'score': 0.008597918786108494},
 {'label': 'disgust', 'score': 0.00843181274831295},
 {'label': 'joy', 'score': 0.0010455820010975003}]

In [11]:
predictions

[[{'label': 'surprise', 'score': 0.7296028733253479},
  {'label': 'neutral', 'score': 0.14038577675819397},
  {'label': 'fear', 'score': 0.06816203892230988},
  {'label': 'joy', 'score': 0.04794236272573471},
  {'label': 'anger', 'score': 0.00915634073317051},
  {'label': 'disgust', 'score': 0.002628473099321127},
  {'label': 'sadness', 'score': 0.002122159581631422}],
 [{'label': 'neutral', 'score': 0.44937023520469666},
  {'label': 'disgust', 'score': 0.273592084646225},
  {'label': 'joy', 'score': 0.10908293724060059},
  {'label': 'sadness', 'score': 0.09362714737653732},
  {'label': 'anger', 'score': 0.040478307753801346},
  {'label': 'surprise', 'score': 0.02697017230093479},
  {'label': 'fear', 'score': 0.006879056338220835}],
 [{'label': 'neutral', 'score': 0.6462165713310242},
  {'label': 'sadness', 'score': 0.24273282289505005},
  {'label': 'disgust', 'score': 0.043422624468803406},
  {'label': 'surprise', 'score': 0.028300536796450615},
  {'label': 'joy', 'score': 0.014211492612957954},
  {'label': 'fear', 'score': 0.014084096997976303},
  {'label': 'anger', 'score': 0.01103188656270504}],
 [{'label': 'fear', 'score': 0.9281684160232544},
  {'label': 'anger', 'score': 0.032190777361392975},
  {'label': 'neutral', 'score': 0.012808679603040218},
  {'label': 'sadness', 'score': 0.00875687226653099},
  {'label': 'surprise', 'score': 0.008597918786108494},
  {'label': 'disgust', 'score': 0.00843181274831295},
  {'label': 'joy', 'score': 0.0010455820010975003}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104178339242935},
  {'label': 'disgust', 'score': 0.006480599287897348},
  {'label': 'fear', 'score': 0.0053939977660775185},
  {'label': 'surprise', 'score': 0.0022869440726935863},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.001733880490064621}],
 [{'label': 'joy', 'score': 0.9327977299690247},
  {'label': 'disgust', 'score': 0.037717387080192566},
  {'label': 'neutral', 'score': 0.015891926363110542},
  {'label': 'sadness', 'score': 0.006444522179663181},
  {'label': 'anger', 'score': 0.005024992395192385},
  {'label': 'surprise', 'score': 0.0015812095953151584},
  {'label': 'fear', 'score': 0.0005423080874606967}],
 [{'label': 'joy', 'score': 0.6528699398040771},
  {'label': 'neutral', 'score': 0.254275381565094},
  {'label': 'surprise', 'score': 0.06808310747146606},
  {'label': 'sadness', 'score': 0.009908986277878284},
  {'label': 'disgust', 'score': 0.006512207444757223},
  {'label': 'anger', 'score': 0.004821314476430416},
  {'label': 'fear', 'score': 0.003529014065861702}],
 [{'label': 'neutral', 'score': 0.5494765639305115},
  {'label': 'sadness', 'score': 0.1116902306675911},
  {'label': 'disgust', 'score': 0.10400673747062683},
  {'label': 'surprise', 'score': 0.07876552641391754},
  {'label': 'anger', 'score': 0.0641336515545845},
  {'label': 'fear', 'score': 0.051362842321395874},
  {'label': 'joy', 'score': 0.040564440190792084}]]

In [12]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.00915634073317051},
 {'label': 'disgust', 'score': 0.002628473099321127},
 {'label': 'fear', 'score': 0.06816203892230988},
 {'label': 'joy', 'score': 0.04794236272573471},
 {'label': 'neutral', 'score': 0.14038577675819397},
 {'label': 'sadness', 'score': 0.002122159581631422},
 {'label': 'surprise', 'score': 0.7296028733253479}]

In [13]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [14]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [15]:
emotion_scores

{'anger': [np.float64(0.0641336515545845),
  np.float64(0.6126195788383484),
  np.float64(0.6126195788383484),
  np.float64(0.0641336515545845),
  np.float64(0.35148394107818604),
  np.float64(0.35148394107818604),
  np.float64(0.08141222596168518),
  np.float64(0.08141222596168518),
  np.float64(0.23222482204437256),
  np.float64(0.23222482204437256)],
 'disgust': [np.float64(0.273592084646225),
  np.float64(0.34828484058380127),
  np.float64(0.34828484058380127),
  np.float64(0.10400673747062683),
  np.float64(0.15072260797023773),
  np.float64(0.15072260797023773),
  np.float64(0.18449503183364868),
  np.float64(0.18449503183364868),
  np.float64(0.7271749377250671),
  np.float64(0.7271749377250671)],
 'fear': [np.float64(0.9281684160232544),
  np.float64(0.942527711391449),
  np.float64(0.942527711391449),
  np.float64(0.9723208546638489),
  np.float64(0.3607065975666046),
  np.float64(0.3607065975666046),
  np.float64(0.09504331648349762),
  np.float64(0.09504331648349762),
  np.float64(0.051362842321395874),
  np.float64(0.051362842321395874)],
 'joy': [np.float64(0.9327977299690247),
  np.float64(0.7044216394424438),
  np.float64(0.7044216394424438),
  np.float64(0.7672365307807922),
  np.float64(0.25188109278678894),
  np.float64(0.25188109278678894),
  np.float64(0.040564440190792084),
  np.float64(0.040564440190792084),
  np.float64(0.04337584227323532),
  np.float64(0.04337584227323532)],
 'sadness': [np.float64(0.6462165713310242),
  np.float64(0.887939453125),
  np.float64(0.887939453125),
  np.float64(0.5494765639305115),
  np.float64(0.7326852083206177),
  np.float64(0.7326852083206177),
  np.float64(0.8843895196914673),
  np.float64(0.8843895196914673),
  np.float64(0.621393084526062),
  np.float64(0.621393084526062)],
 'surprise': [np.float64(0.9671575427055359),
  np.float64(0.1116902306675911),
  np.float64(0.1116902306675911),
  np.float64(0.1116902306675911),
  np.float64(0.1116902306675911),
  np.float64(0.1116902306675911),
  np.float64(0.47588053345680237),
  np.float64(0.47588053345680237),
  np.float64(0.1116902306675911),
  np.float64(0.1116902306675911)],
 'neutral': [np.float64(0.7296028733253479),
  np.float64(0.2525447607040405),
  np.float64(0.2525447607040405),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.07876552641391754),
  np.float64(0.27190229296684265),
  np.float64(0.27190229296684265)]}

In [16]:
from tqdm import tqdm

# tqdm is a fast, lightweight Python library that adds a visual progress bar to your loops and iterables

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5308/5308 [57:46<00:00,  1.53it/s]

In [22]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [18]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273592,0.928168,0.932798,0.646217,0.967158,0.729603,9780002005883
1,0.612620,0.348285,0.942528,0.704422,0.887939,0.111690,0.252545,9780002261982
2,0.612620,0.348285,0.942528,0.704422,0.887939,0.111690,0.252545,9780002261982
3,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078766,9780006178736
4,0.351484,0.150723,0.360707,0.251881,0.732685,0.111690,0.078766,9780006280897
...,...,...,...,...,...,...,...,...
5303,0.148209,0.030642,0.919165,0.255170,0.853722,0.980877,0.030656,9788172235222
5304,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765,9788173031014
5305,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625,9788179921623
5306,0.064134,0.104007,0.459269,0.759456,0.951104,0.368111,0.078766,9788185300535
5307,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766,9789027712059

In [19]:
books = pd.merge(books, emotions_df, on = "isbn13")

In [20]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273592,0.928168,0.932798,0.646217,0.967158,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612620,0.348285,0.942528,0.704422,0.887939,0.111690,0.252545
2,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612620,0.348285,0.942528,0.704422,0.887939,0.111690,0.252545
3,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612620,0.348285,0.942528,0.704422,0.887939,0.111690,0.252545
4,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612620,0.348285,0.942528,0.704422,0.887939,0.111690,0.252545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5525,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction,0.148209,0.030642,0.919165,0.255170,0.853722,0.980877,0.030656
5526,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765
5527,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625
5528,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459269,0.759456,0.951104,0.368111,0.078766
5529,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766

In [23]:
books.to_csv("books_with_emotions.csv", index = False)